name: Linux build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Update OS repositories
      run: sudo apt-get update
    - name: Setup test environment
      run: sudo apt-get -y install make g++ git python python-matplotlib qt5-default libqt5xmlpatterns5-dev libqt5sql5-mysql libqt5charts5-dev libbz2-dev liblzma-dev zlib1g-dev
    - name: Update submodules
      run: git submodule update --recursive --init
    - name: Build dependencies
      run: make build_3rdparty build_libs_release build_tools_release build_gui_release
  tests:
    runs-on: ubuntu-18.04
    needs: build
    - name: Run tests
      run: make -k test_lib test_tools
